version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.7
        commands:
            - pip install --upgrade pip
            # Install dependencies needed for running the static analysis
            - pip install -r requirements.txt pylint
    pre_build:
        commands:
            - python --version
            - pylint --disable=C,R0903,C0114,E1101,W0611,E0611,R1710,W0404,W0613,R1705,E0307,E0401 *.py **/*.py
            
artifacts:
    files:
        - '**/*'